feat: module to be easier test hot updated vuex stores
Farm-Investimentos/front-mfe-libs-ts pull request #107
Opened 2023-04-20 12:13 UTC by waverapha

This module has the purpose to allow update Vuex modules (getters, actions, mutations, state) using hot update in a simpler way.

2023-04-20 12:29 UTC, christian-benseler-farm commented
@waverapha faz pouco sentido ao meu ver essa implementação estar aqui, pois vai deixar o pacote libs-ts que é usado em produção mais pesado com código que é usado apenas para testes.
Se fosse pra fazer, faria mais sentido ser um projeto a parte que seria importado apenas em _devDepencency_ nos demais projetos.

E tem alguns problemas, como a versão do Vue usada (está ^2.7.14 mas a gente tem fixada a 2.7.10 nos projetos) e uma questão de mudar código de produção apenas para atender testes, como a mudança feita no src/helpers/store/index.ts
Faria mais sentido mudar isso apenas no setup do jest ou em cada componente.

2023-04-20 12:29 UTC, christian-benseler-farm requested changes
Checar meu comentário geral a respeito dessa implementação.

2023-04-20 13:48 UTC, waverapha commented
> @waverapha faz pouco sentido ao meu ver essa implementação estar aqui, pois vai deixar o pacote libs-ts que é usado em produção mais pesado com código que é usado apenas para testes. Se fosse pra fazer, faria mais sentido ser um projeto a parte que seria importado apenas em _devDepencency_ nos demais projetos.
> 
> E tem alguns problemas, como a versão do Vue usada (está ^2.7.14 mas a gente tem fixada a 2.7.10 nos projetos) e uma questão de mudar código de produção apenas para atender testes, como a mudança feita no src/helpers/store/index.ts Faria mais sentido mudar isso apenas no setup do jest ou em cada componente.

@christian-benseler-farm Bom, a primeira pergunta seria: na sua opinião essa implementação como um todo vale a pena? * Eu segui fazendo por achar que vale considerando o uso do Vuex pra gerenciar estados de request e dados também.

Podemos publicar como um pacote separado sim (aqui no repo da farm?), até acho que faz mais sentido também ser uma coisa separada mais como uma "ponte" entre o jest e o vuex. Vale só salientar que nesse caso aqui o vue e vuex só foram instalados mais por conta dos testes unitários e tipagem.

Olhando por esse ponto de vista em relação a produção realmente não faz sentido manter aqui e muito menos importar no index.ts. Eu assumi que esse projeto tinha tree shaking e teria como fazermos ele buildar somente o importado nos projetos (o que faria importarmos isso só nos testes e não iria pra prod no bundle final de qualquer forma).

Sobre a versão do Vue, podemos mudar também sem problema se for o caso de seguir em frente.

2023-04-25 10:50 UTC, christian-benseler-farm approved these changes

2023-04-25 10:50 UTC, merged